### ISSUE TITLE
Library shows "new episodes" icon (plus sign) when show is empty

### ISSUE THREAD

**Issue by piejanssens** [paulsalem/skin.refocus.big#5]
From time to time I delete seasons from certain TV shows that I don't mind loosing in order to free up some space. I noticed that when there are no more seasons around. Delete all seasons, clean library (but keep the main show folder + fanart) then it looks like there are new eps for that show in the library.

**Comment by paulsalem** [comment]
Is this happening on the master branch, (frodo nightlies), on the eden branch, or on 0.83.1 version?
Latest nightly does not offer the option to show overlays on unwatched or on progress episodes, only on watched ones.
I removed the option in order to avoid confusion. I might re-add it along the road depending on the feedback.

**Comment by piejanssens** [comment]
It was happening on Eden branch, I'm now on Frodo.
I really hope you'll re-add it then Paul, I really loved the option to show unwatched!

**Comment by paulsalem** [comment]
Don't worry. I will eventually re-add the show unwatched option.

**Comment by piejanssens** [comment]
Awesome!
